### ISSUE TITLE
保存还有中文的wiki页面时，gitlab出现500错误

### ISSUE THREAD

**Issue by oylbin** [NDHWAlliance/gitlab-analytics#20]
错误信息如下：

```
Started PUT "/Owen/gitlab-analytics/wikis/home" for 172.16.146.114 at 2018-07-25 12:06:25 +0800
Processing by Projects::WikisController#update as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "wiki"=>{"last_commit_sha"=>"2fe422f4ac63ef8043c6d5f44cc058ea50b5cd4d", "title"=>"home", "format"=>"markdown", "content"=>"[FILTERED]", "message"=>"Update home"}, "namespace_id"=>"Owen", "project_id"=>"gitlab-analytics", "id"=>"home"}
Started POST "/api/v4/internal/allowed" for 127.0.0.1 at 2018-07-25 12:06:25 +0800
Started POST "/api/v4/internal/pre_receive" for 127.0.0.1 at 2018-07-25 12:06:25 +0800
Started POST "/api/v4/internal/post_receive" for 127.0.0.1 at 2018-07-25 12:06:25 +0800
Completed 500 Internal Server Error in 320ms (ActiveRecord: 3.4ms)
Encoding::UndefinedConversionError ("\xE6" from ASCII-8BIT to UTF-8):
config/initializers/forbid_sidekiq_in_transactions.rb:35:in `block (2 levels) in <module:NoEnqueueingFromTransactions>'
app/services/web_hook_service.rb:63:in `async_execute'
app/models/hooks/web_hook.rb:16:in `async_execute'
app/models/project.rb:1122:in `block (2 levels) in execute_hooks'
app/models/project.rb:1121:in `block in execute_hooks'
lib/after_commit_queue.rb:27:in `instance_eval'
lib/after_commit_queue.rb:27:in `run_after_commit_or_now'
app/models/project.rb:1120:in `execute_hooks'
app/services/wiki_pages/base_service.rb:7:in `execute_hooks'
app/services/wiki_pages/update_service.rb:5:in `execute'
app/controllers/projects/wikis_controller.rb:48:in `update'
lib/gitlab/i18n.rb:51:in `with_locale'
lib/gitlab/i18n.rb:57:in `with_user_locale'
app/controllers/application_controller.rb:362:in `set_locale'
lib/gitlab/middleware/multipart.rb:97:in `call'
lib/gitlab/request_profiler/middleware.rb:14:in `call'
lib/gitlab/middleware/go.rb:17:in `call'
lib/gitlab/etag_caching/middleware.rb:11:in `call'
lib/gitlab/middleware/read_only/controller.rb:38:in `call'
lib/gitlab/middleware/read_only.rb:16:in `call'
lib/gitlab/request_context.rb:18:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
lib/gitlab/middleware/release_env.rb:10:in `call'
```

**Comment by oylbin** [comment]
有问题的环境

GitLab 11.1.1 (94b9323)
GitLab Shell 7.1.4
GitLab Workhorse v5.0.0
GitLab API v4
Ruby 2.4.4p296
Rails 4.2.10
postgresql 9.6.8

**Comment by oylbin** [comment]
在 ga server 上抓包，发现gitlab报错的时候，ga server根本就没有收到任何请求……

这说明gitlab出错并不是 ga web hook响应值的问题。

但是，确实在项目里移除了 ga web hook之后，保存wiki时就不会报500了。

为啥，好奇怪。

**Comment by oylbin** [comment]
如果要保存的wiki内容里没有中文，就不会报错…… ga webhook 也可以正常收到通知。

难道是gitlab的bug？

**Comment by oylbin** [comment]
https://blog.csdn.net/xiaofei125145/article/details/77540395  留着看看

**Comment by yourfccoder** [comment]
https://blog.csdn.net/alittleyatou/article/details/80333119
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3307#note_64245578
试试这个 @oylbin ，api修改和web端admin修改都是一样的好多人都提到

**Comment by oylbin** [comment]
根据目前的现象来看，应该是 gitlab 11.x 的问题。

公司内网gitlab，版本11.1.2。
现象：
任何一个项目，配置一个不存在的webhook，比如`http://example.com/test.json`，trigger勾选上`Wiki Page events`。
然后在项目wiki里保存任何包含中文的wiki是，报500错误。

我在外网的一个10.5.3版本的gitlab上不能复现此问题。

**Comment by oylbin** [comment]
成功在 https://gitlab.com/oylbin/test/wikis 上复现此问题。我要去给gitlab提issue了，😓

**Comment by oylbin** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/49745

**Comment by yourfccoder** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20906

更新到11.2是否能修复 @oylbin
