### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by exhui** [NDHWAlliance/gitlab-analytics#28]
使用对应的地址和私钥，可以使用post调用成功
输入GitLab URL和GitLab Private Token，commit后报错

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

  | Traceback (most recent call last):
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
ga         |     response = self.full_dispatch_request()
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
ga         |     rv = self.handle_user_exception(e)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
ga         |     reraise(exc_type, exc_value, tb)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
ga         |     raise value
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
ga         |     rv = self.dispatch_request()
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
ga         |     return self.view_functions[rule.endpoint](**req.view_args)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
ga         |     return func(*args, **kwargs)
ga         |   File "/app/ga/routes.py", line 117, in hooks
ga         |     projects = gitlabservice.get_projects()
ga         |   File "/app/ga/services/gitlabservice.py", line 31, in get_projects
ga         |     if is_hooked(project):
ga         |   File "/app/ga/services/gitlabservice.py", line 20, in is_hooked
ga         |     for hook in project.hooks.list():
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/exceptions.py", line 244, in wrapped_f
ga         |     raise error(e.error_message, e.response_code, e.response_body)
ga         | gitlab.exceptions.GitlabListError: 403: 403 Forbidden
ga         | 172.17.0.1 - - [31/Jul/2020 11:34:58] "GET /hooks HTTP/1.1" 500 -

**Comment by rcoltea** [comment]
Did you find a solution for this?

**Comment by oylbin** [comment]
Does your access token have complete read/write access to the API?
